### ISSUE TITLE
Accept request header wordt genegeerd

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#1143]
```
curl --location --request POST 'http://localhost:5001/haalcentraal/brp/proxy/api/v2/personen' \
--header 'Content-Type: application/json' \
--header 'Accept: application/xml' \
--data-raw '{
    "fields": ["aNummer", "burgerservicenummer","geslacht","naam","geboorte" ],
    "type": "RaadpleegMetBurgerservicenummer",
    "burgerservicenummer": [ "555550101" ]
}'
```

Dit levert een response in json, terwijl xml is gevraagd. De API ondersteunt geen xml, dus zou hier denk ik een 406 Not Acceptable
"Gevraagde contenttype wordt niet ondersteund." als response moeten komen.

**Comment by fsamwel** [comment]
@MelvLee wanneer ik nu een request doe zonder Accept header, krijg ik een 406 "Gevraagde contenttype wordt niet ondersteund."

De accept header is niet verplicht toch?

**Comment by fsamwel** [comment]
Oh, het is iets anders,

Bij Accept: */* krijg ik een 406
Bij volledig weglaten van de Accept header krijg ik een 500 "Internal Server error."
> requestBody: {requestBody}
[Event](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/issues/1143)
[Level (Error)](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/issues/1143)
[Type (0xEEF9B4A9)](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/issues/1143)
[Export](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/issues/1143)
ConnectionId
0HMIDS43LUL7C
ExceptionDetail
{Type: 'System.IndexOutOfRangeException', HResult: -2146233080, Message: 'Index was outside the bounds of the array.', Source: 'Microsoft.Extensions.Primitives', TargetSite: 'System.String OutOfBounds()'}
ParentId
0000000000000000
RequestId
0HMIDS43LUL7C:0000002B
RequestPath
/haalcentraal/brp/proxy/api/v2/personen
SourceContext
BrpProxy.Middlewares.OverwriteResponseBodyMiddleware
SpanId
e2bbb75f004edc91
TraceId
dc33ed7c7041b76e856edbd39f1b148a
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Microsoft.Extensions.Primitives.StringValues.OutOfBounds()
   at BrpProxy.Middlewares.FoutHandlers.AcceptIsAllowed(HttpContext context, Stream orgResponseBodyStream, ILogger logger) in /src/src/BrpProxy/Middlewares/FoutHandlers.cs:line 203
   at BrpProxy.Middlewares.OverwriteResponseBodyMiddleware.Invoke(HttpContext context) in /src/src/BrpProxy/Middlewares/OverwriteResponseBodyMiddleware.cs:line 111
